spring.application.name=mahliyoedu

# Database ulanish
spring.datasource.url=jdbc:postgresql://localhost:5432/mahliyoedu
spring.datasource.username=postgres
spring.datasource.password=09255432

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080