spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mahliyoedu}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:09255432}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8080}

imagekit.public-key=${IMAGEKIT_PUBLIC_KEY:public_7i4PmDt7KSvmLq8s5PCb+W}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY:private_OxmsExSR7sX3bcOzjrrYLj7n/Lo=}
imagekit.url-endpoint=${IMAGEKIT_URL_ENDPOINT:https://ik.imagekit.io/mahliyoedu}
